name: papersy
description: OU question papers and notes

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.5+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  #Architecture/State Management
  async_redux: ^7.0.2

  #Firebase
  firebase_storage: ^7.0.0
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  google_sign_in: ^4.5.9
  firebase_messaging: ^8.0.0-dev.14
  firebase_in_app_messaging: ^0.3.0+1

  #I/O
  permission_handler: ^5.0.1+1
  file_picker: ^2.1.5
  open_file: ^3.0.3
  flutter_downloader: ^1.5.2
  connectivity: ^2.0.2
  share: ^0.6.5+4
  url_launcher: ^5.7.10
  filesize: ^1.0.4
  filex: ^0.3.0
  device_info: ^1.0.0
  path_provider: ^1.6.27
  # filex:
  #   git:
  #     url: https://github.com/mdmohsin7/filex
  #     ref: dev

  #MISC
  equatable: ^1.2.5
  webview_flutter: ^1.0.7 
  flutter_conditional_rendering: ^1.1.1
  year_picker:
    path: packages/year_picker

  #UI/animations
  flutter_signin_button: ^1.1.0
  flutter_svg: ^0.19.1
  feature_discovery: ^0.13.0
  font_awesome_flutter: ^8.11.0
  animations: ^1.1.2
  smart_select: ^4.3.2

  #Sealed Classes/Unions
  freezed_annotation:

  #ADS
  firebase_admob: ^0.11.0+1

  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/account.svg
    - assets/profile.svg
    - assets/no_data.svg
    - assets/logo.svg
    - assets/error.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
